module.exports =  {
	data: {
		plotPoints: [
			{ id:1, 
				name:'The Fires of Escalon', 
				description:'<p>The ravaging hordes are coming and a party of elven scouts must deny them sustenance.</p>'                
			}],
		races: [],
		skills: [],
		edges: [],
		hindrances: [],
		gear: [],
		places:[],
		archetypes: [],
		characters: [],
		extras: [],
		beasts: [],
		powers: [],
		standardCharacters: [{ id:1,
			name: "Standard Character 1",
			description: "<p>Standard Character 1 Description.</p>"},
			{ id: 2,
			name: "Standard Character 2",
			description: "<p>Standard Character 2 Description.</p>"}],
		standardExtras: [{ id:1,
			name: "Standard Extra 1",
			description: "<p>Standard Extra 1 Description.</p>"},
			{ id: 2,
			name: "Standard Extra 2",
			description: "<p>Standard Extra 2 Description.</p>"}],
		standardPowers: [{ id:1,
			name: "Standard Power 1",
			description: "<p>Standard Power 1 Description.</p>"},
			{ id: 2,
			name: "Standard Power 2",
			description: "<p>Standard Power 2 Description.</p>"}],
		standardBeasts: [{ id:1,
			name: "Standard Beast 1",
			description: "<p>Standard Beast 1 Description.</p>"},
			{ id: 2,
			name: "Standard Beast 2",
			description: "<p>Standard Beast 2 Description.</p>"}]
	}
	
}