repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
  - repo: local
    hooks:
      - id: npm-audit
        name: npm security audit
        entry: bash -c 'cd ui-web && npm audit --audit-level=high'
        language: system
        pass_filenames: false
        always_run: true
