import {createConstants} from '../utils';

export default createConstants(
  "API_RESULT_SUCCESS",
  "API_RESULT_FAILURE",
  "API_STATUS_STARTED",
  "API_STATUS_FINISHED",
  "DISPLAY_MESSAGE",
  "MESSAGE_CONTEXT_DANGER",
  "MESSAGE_CONTEXT_INFO",
  "MESSAGE_CONTEXT_SUCCESS",
  "MESSAGE_CONTEXT_WARNING"
)