/**
 * Created by JimBarrows on 4/21/18.
 */
import {createConstants} from '../utils';

export default createConstants(
		'PLOT_POINT_CANCEL',
		'PLOT_POINT_CREATE',
		'PLOT_POINT_DESCRIPTION_CHANGE',
		'PLOT_POINT_LOAD_BEGIN',
		'PLOT_POINT_LOAD_SUCCESS',
		'PLOT_POINT_LOAD_FAILURE',
		'PLOT_POINT_MAXIMUM_ATTRIBUTE_POINT_CHANGE',
		'PLOT_POINT_MAXIMUM_MAJOR_HINDRANCE_CHANGE',
		'PLOT_POINT_MAXIMUM_MINOR_HINDRANCE_CHANGE',
		'PLOT_POINT_MAXIMUM_SKILL_POINTS_CHANGE',
		'PLOT_POINT_NAME_CHANGE',
		'PLOT_POINT_NEW',
		'PLOT_POINT_RACE_CHANGE',
		'PLOT_POINT_SAVE_BEGIN',
		'PLOT_POINT_SAVE_FAILURE',
		'PLOT_POINT_SAVE_SUCCESS',
);