/**
 * Created by JimBarrows on 4/21/18.
 */
import {createConstants} from '../utils';

export default createConstants(
		'PLOT_POINT_ADD_BEGIN',
		'PLOT_POINT_ADD_SUCCESS',
		'PLOT_POINT_ADD_FAILURE',
		'PLOT_POINT_LOAD_BEGIN',
		'PLOT_POINT_LOAD_SUCCESS',
		'PLOT_POINT_LOAD_FAILURE',
		'PLOT_POINT_NOT_FOUND',
		'PLOT_POINT_UPDATE_BEGIN',
		'PLOT_POINT_UPDATE_FAILURE',
		'PLOT_POINT_UPDATE_SUCCESS',
		'PLOT_POINT_NEW'
);