var {After, Before} = require('cucumber')

Before(function (result) {
  return this.swga_db.none("delete from ammunition_gear_note")
  .then(() => this.swga_db.none("delete from armor_gear_note"))
  .then(() => this.swga_db.none("delete from beast_monstrous_ability"))
  .then(() => this.swga_db.none("delete from beast_skill"))
  .then(() => this.swga_db.none("delete from character_ammunition"))
  .then(() => this.swga_db.none("delete from character_edge"))
  .then(() => this.swga_db.none("delete from character_hand_weapon"))
  .then(() => this.swga_db.none("delete from character_hindrance"))
  .then(() => this.swga_db.none("delete from character_mundane_item"))
  .then(() => this.swga_db.none("delete from character_power"))
  .then(() => this.swga_db.none("delete from edge_edge_requirement"))
  .then(() => this.swga_db.none("delete from edge_requirements"))
  .then(() => this.swga_db.none("delete from hand_weapon_gear_note"))
  .then(() => this.swga_db.none("delete from mundane_item_gear_note"))
  .then(() => this.swga_db.none("delete from ammunition"))
  .then(() => this.swga_db.none("delete from power_arcane_backgrounds"))
  .then(() => this.swga_db.none("delete from arcane_backgrounds"))
  .then(() => this.swga_db.none("delete from armors"))
  .then(() => this.swga_db.none("delete from beasts"))
  .then(() => this.swga_db.none("delete from characters"))
  .then(() => this.swga_db.none("delete from edges"))
  .then(() => this.swga_db.none("delete from edge_types"))
  .then(() => this.swga_db.none("delete from gear_notes"))
  .then(() => this.swga_db.none("delete from hand_weapons"))
  .then(() => this.swga_db.none("delete from hindrances"))
  .then(() => this.swga_db.none("delete from monstrous_abilities"))
  .then(() => this.swga_db.none("delete from mundane_items"))
  .then(() => this.swga_db.none("delete from powers"))
  .then(() => this.swga_db.none("delete from skills"))
  .then(() => this.swga_db.none("delete from technology_levels"))
  .then(() => this.swga_db.none("delete from trapping_effects"))
  .then(() => this.swga_db.none("delete from trappings"))
  .then(() => this.swga_db.none("delete from gear_category"))
  .then(() => this.swga_db.none("delete from plot_points"))
  .then(() => this.user_db.none("delete from user_login"))

})

After(function () {
})

