import {createConstants} from "../utils";

export default createConstants(
		'PLOT_POINT_ADD_BEGIN', "PLOT_POINT_ADD_SUCCESS", "PLOT_POINT_ADD_FAILURE",
		"PLOT_POINTS_LOAD_BEGIN", "PLOT_POINTS_LOAD_SUCCESS", "PLOT_POINTS_LOAD_FAILURE",
		"PLOT_POINT_EDIT",
		"PLOT_POINT_NOT_FOUND",
		"PLOT_POINT_UPDATE_SUCCESS", "PLOT_POINT_UPDATE_BEGIN", "PLOT_POINT_UPDATE_FAILURE", "PLOT_POINT_NEW",
		"PLOT_POINT_DELETE_BEGIN", "PLOT_POINT_DELETE_SUCCESS", "PLOT_POINT_DELETE_FAILURE"
);
