/**
 * Created by JimBarrows on 7/3/16.
 */

export const UserEventNames = {
	REGISTER_USER_BEGINS: "REGISTER_USER_BEGINS"
	, REGISTER_USER_FAILURE: "REGISTER_USER_FAILURE"
	, USER_LOGGED_IN: "USER_LOGGED_IN"
	, USER_LOGGED_OUT: "USER_LOGGED_OUT"
	, USER_LOGIN_FAILURE: "USER_LOGIN_FAILURE"
	, USER_LOGIN_BEGINS: "USER_LOGIN_BEGINS"
	, USER_LOGOUT_FAILURE: "USER_LOGOUT_FAILURE"
};

export const PlotPointEvent = {
	ADD_RACE: "PLOT_POINT_EVENT_ADD_RACE",
	CREATE_FAILURE: "PLOT_POINT_EVENT_CREATE_FAILURE",
	CREATE_SUCCESS: "PLOT_POINT_EVENT_CREATE_SUCCESS",
	EDIT: "PLOT_POINT_EVENT_EDIT",
	EDITABLE: "PLOT_POINT_EVENT_EDITABLE",
	LOAD_FAILURE: "PLOT_POINT_EVENT_LOAD_FAILURE",
	LOAD_SUCCESS: "PLOT_POINT_EVENT_LOAD_SUCCESS",
	NEW: "PLOT_POINT_EVENT_NEW",
	NOT_FOUND: "PLOT_POINT_NOT_FOUND",
	REMOVE_FAILURE: "PLOT_POINT_FAILURE",
	REMOVE_SUCCESS: "PLOT_POINT_SUCCESS",
	SAVE_FAILURE: "PLOT_POINT_SAVE_FAILURE",
	SAVE_SUCCESS: "PLOT_POINT_SAVE_SUCCESS",
	UPDATE_FAILURE: "PLOT_POINT_UPDATE_FAILURE",
	UPDATE_SUCCESS: "PLOT_POINT_UPDATE_SUCCESS"

};