(in-package :cl-ddd)

(defun add-user( name password)
  (when (string= "" name)
    (return-from add-user "{ \"username\" : [\"Username cannot be blank\"]}"))
  (when (string= "" password)
    (return-from add-user "{ \"password\" : [\"Password cannot be blank\"]}"))
  (when (username-exists-p *user-repository* (username new-user))
    (return-from add-user "{ \"username\" : [\"Username exists\"]}"))
  (let ((new-user (make-instance 'user :username name :password password)))
    (add *user-repository* new-user)
    (return-from add-user new-user)))
