// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
	"aws_project_region"                : "us-west-2",
	"aws_cognito_identity_pool_id"      : "us-west-2:6943af96-eee8-4a29-8245-d2874b525e17",
	"aws_cognito_region"                : "us-west-2",
	"aws_user_pools_id"                 : "us-west-2_1O83ORiU0",
	"aws_user_pools_web_client_id"      : "16e9rp1dekhp08bq5he0o12r4k",
	"aws_appsync_graphqlEndpoint"       : "https://eipwvq2dufahpaygkjpx4x3r5m.appsync-api.us-west-2.amazonaws.com/graphql",
	"aws_appsync_region"                : "us-west-2",
	"aws_appsync_authenticationType"    : "AMAZON_COGNITO_USER_POOLS",
	"aws_content_delivery_bucket"       : "swvtt-20190329084646-hostingbucket-dev",
	"aws_content_delivery_bucket_region": "us-west-2",
	"aws_content_delivery_url"          : "http://swvtt-20190329084646-hostingbucket-dev.s3-website-us-west-2.amazonaws.com",
	"aws_dynamodb_all_tables_region"    : "us-west-2",
	"aws_dynamodb_table_schemas"        : [
		{
			"tableName": "plotpoints-dev",
			"region"   : "us-west-2"
		}
	]
};


export default awsmobile;
