// WARNING: DO NOT EDIT. This file is Auto-Generated by AWS Mobile Hub. It will be overwritten.

// Copyright 2017-2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.

// AWS Mobile Hub Project Constants
const awsmobile = {
    'aws_app_analytics': 'enable',
    'aws_cloud_logic': 'enable',
    'aws_cloud_logic_custom': [{"id":"12p2eek3i8","name":"sampleCloudApi","description":"","endpoint":"https://12p2eek3i8.execute-api.us-west-2.amazonaws.com/Development","region":"us-west-2","paths":["/items","/items/123"]},{"id":"w58uasm85l","name":"PlotPointsCRUD","description":"","endpoint":"https://w58uasm85l.execute-api.us-west-2.amazonaws.com/Development","region":"us-west-2","paths":["/PlotPoints","/PlotPoints/123"]}],
    'aws_cognito_identity_pool_id': 'us-west-2:b0016b50-607e-4831-af7e-5f40abd252b8',
    'aws_cognito_region': 'us-west-2',
    'aws_content_delivery': 'enable',
    'aws_content_delivery_bucket': 'savageworldsvirtualt-hosting-mobilehub-800734882',
    'aws_content_delivery_bucket_region': 'us-west-2',
    'aws_content_delivery_cloudfront': 'enable',
    'aws_content_delivery_cloudfront_domain': 'd17opd9sdou2db.cloudfront.net',
    'aws_dynamodb': 'enable',
    'aws_dynamodb_all_tables_region': 'us-west-2',
    'aws_dynamodb_table_schemas': [{"tableName":"savageworldsvirtualt-mobilehub-800734882-PlotPoints","attributes":[{"name":"userId","type":"S"},{"name":"name","type":"S"},{"name":"description","type":"S"}],"indexes":[],"region":"us-west-2","hashKey":"userId","rangeKey":"name"}],
    'aws_mobile_analytics_app_id': 'd0ac95c6df274d508af51c6fcdc7ab00',
    'aws_mobile_analytics_app_region': 'us-east-1',
    'aws_project_id': '5016e856-dd8e-4c32-8054-f41704d69a4b',
    'aws_project_name': 'Savage Worlds Virtual Table Top',
    'aws_project_region': 'us-west-2',
    'aws_resource_bucket_name': 'savageworldsvirtualt-deployments-mobilehub-800734882',
    'aws_resource_name_prefix': 'savageworldsvirtualt-mobilehub-800734882',
    'aws_sign_in_enabled': 'enable',
    'aws_user_pools': 'enable',
    'aws_user_pools_id': 'us-west-2_29mjXEP3R',
    'aws_user_pools_mfa_type': 'ON',
    'aws_user_pools_web_client_id': '4i8d7pm4f9n5tq1ekl9nrc9oe3',
}

export default awsmobile;
